name: Publish to Docker Registry
on:
  # release:
  #     types: [published]
  #push:
    #branches:
    #  - main    
  #schedule:
   # - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
  # workflow_run:
  #   workflows: ["SLSA Go releaser"]
  #   types:
  #     - completed
  workflow_dispatch:
  
jobs:
  build_docker_and_publish:    
    runs-on: ubuntu-latest
     steps:
     
      - name: Clone repository
        uses: actions/checkout@v2
        # with:
        #   ref: ${{ steps.vars.outputs.tag }}

      - name: Read version from release.json
        uses: notiz-dev/github-action-json-property@release
        id: xteve_version
        with:
          path: 'release.json'
          prop_path: 'version' 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ranking:${{ steps.xteve_version.outputs.prop }}
